# Generated by Django 5.1.1 on 2024-10-01 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_layanan_deskripsi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pemesan', models.CharField(max_length=255)),
                ('berat_cucian', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_harga', models.IntegerField()),
                ('id_layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundry.layanan')),
            ],
        ),
    ]
